language: c

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env:
        - CMAKE_OPTS="-DCUCKOO_MODULE=ON -DMAGIC_MODULE=ON -DYARA_TESTS=ON -DYARA_ADDRESS_SANITIZER=ON"
        - RUN_TESTS=true
      # The certificate for scan.coverity.com is too new and is not recognized by
      # wget. This command adds the certificate to /etc/ssl/certs/ca-certificates.crt
      # See: https://github.com/travis-ci/travis-ci/issues/6142
      #before_install: echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      install:
        - sudo apt-get update
        - sudo apt-get install -y bison flex libjansson-dev libmagic-dev libssl-dev
    - os: linux
      dist: xenial
      sudo: required
      env:
        - CMAKE_OPTS="-DCMAKE_C_FLAGS=-m32 -DCUCKOO_MODULE=ON -DMAGIC_MODULE=ON -DYARA_TESTS=ON"
        - RUN_TESTS=true
      install:
        - sudo dpkg --add-architecture i386
        - sudo rm -rf /etc/apt/sources.list.d/
        - sudo apt-get update
        #- sudo apt-get remove -y postgresql $(sudo dpkg --get-selections | grep libmagic | cut -f1) file
        #- sudo apt-get remove -y postgresql $(sudo dpkg --get-selections | grep libmagic | cut -f1) file
        #- sudo apt-get clean
        - sudo apt-get remove -y libmagic1 libmagic-dev openssl libssl-dev
        - sudo apt-get install -y bison flex gcc-multilib libjansson-dev:i386 libssl-dev:i386
        - sudo apt-get download libmagic-dev:i386 libmagic1:i386
        - sudo dpkg -i libmagic*.deb
    - os: linux
      dist: xenial
      sudo: required
      env:
        - CMAKE_OPTS="-DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_SYSTEM_NAME=Windows"
      install:
        - sudo apt-get update
        - sudo apt-get install -y gcc-mingw-w64
    - os: linux
      dist: xenial
      sudo: required
      env:
        - CMAKE_OPTS="-DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_SYSTEM_NAME=Windows"
      install:
        - sudo apt-get update
        - sudo apt-get install -y gcc-mingw-w64
    - os: osx
      osx_image: xcode7.3
      env:
        - PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
        - CMAKE_OPTS="-DCMAKE_INCLUDE_PATH=/usr/local/opt/flex/include -DCMAKE_LIBRARY_PATH=/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"
      install:
        - brew update
        - brew install flex bison
    - os: osx
      osx_image: xcode8.3
      env:
        - PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
        - CMAKE_OPTS="-DCMAKE_INCLUDE_PATH=/usr/local/opt/flex/include -DCMAKE_LIBRARY_PATH=/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"
      install:
        - brew install flex bison
    - os: osx
      osx_image: xcode9.2
      env:
        - PATH="/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:$PATH"
        - CMAKE_OPTS="-DCMAKE_INCLUDE_PATH=/usr/local/opt/flex/include -DCMAKE_LIBRARY_PATH=/usr/local/opt/flex/lib;/usr/local/opt/bison/lib"
      install:
        - brew update
        - brew install flex bison

script:
  - rm -rf build && mkdir build
  - cd build
  - cmake ${CMAKE_OPTS} ..
  - cmake --build . -- -j
  - if [ "$RUN_TESTS" = "true" ]; then ctest -V; fi

#env:
#  global:
#    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
#    # via the "travis encrypt" command using the project repo's public key
#    - secure: "JWobvJ94pWt/xVciQURkNFS3I+gyu2IyZPKYEs6HDlHrpHs4BoVDZeRjmgx0s6aDeQjKJHowGDu17IlbnCkKzXrZErEJkA+Oc/d0SwgXKiUU9WYiaGBJjJUoYZw66QIEuGGKkF4uQ7EIcW/vN7wzrCDyAiPeOPUjVP4Tc2XRzmkSfakfmf9cE5nqT84DPUYiRegM7iepMrZi9kEaAoboBuETT+6eUKdERRadM0QNjZmCYMEMjtFj3lE51Ey2stGqZdKJvJN0FUmxGoaXCFFAsNmZPnFeDkqTf0a+MzxG2m4nnIXyNC/nT5XLItKHog4KROHb4tUpCZJ4iJhcw3loWMCtkZqB2fq2PaOkKk2zxPr3HLCn7ltmOzReBEDjEg68UqWydRW5534JGosbcA9IfshS1VqnZLgGwQHieXNeqhJUumt1DpON7AQEiEzbzAk0y2VcPlDPuCt9QS1k+zPMZLzbwgvs1ZOH39oFESW+iEDdzZjbhyC3J6azTHFcnA7r5SsYe1pzcSUaYtS1ehhb0lU/442JSHw2j00Nv9qFycYNvDrRNQNBxLziVustT0WJoVdFlkKy16iu1tUYOVXKgmMfqUDINfU6zRz3DskVuB9MZzq/4cMdK4jMRIDNZWvye1BzM7o/PiJoNaQc/6iav2RD+5YV46bBr60TqnYyjlM="

#addons:
#  coverity_scan:
#    project:
#      name: "plusvic/yara"
#      description: "Build submitted via Travis CI"
#    notification_email: plusvic@gmail.com
#    build_command_prepend: "./configure; make clean"
#    build_command:   "make -j 4"
#    branch_pattern: master
