# AppVeyor CI for Windows

version: 3.9.0-{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  matrix:
  - TARGET: cygwin
    CMAKE_OPTS: -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015"
    configuration: Release
    platform: x86
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015"
    configuration: Debug
    platform: x86
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015 Win64"
    platform: x64
    configuration: Release
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015 Win64"
    platform: x64
    configuration: Debug

for:
  - matrix:
      only:
        - TARGET: cygwin
    install:
      - cmd: C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages bison,cmake,cygwin-devel,flex,gcc-core,file-devel,libjansson-devel,make,pkg-config
    build_script:
      - cmd: C:\cygwin64\bin\bash -e -l -c "cd c:/projects/yara && ./build.sh"
  - matrix:
      only:
        - TARGET: vs2015
    install:
      - cmd: choco install -Y winflexbison3
    build_script:
      - cmd: mkdir build
      - cmd: cd build
      - cmd: cmake %CMAKE_OPTS% ..
      - cmd: cmake --build . --config %configuration% -- -m

test_script:
  - cmd: cd C:\projects\yara\build
  - cmd: ctest -V

# Uncomment the lines below for enabling Remote Desktop in the Appveyor. This
# allows connecting to the remote machine and debug issues.
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
