# AppVeyor CI for Windows

version: 3.9.0-{build}

pull_requests:
  do_not_increment_build_number: true

environment:
  matrix:
  - TARGET: cygwin
    CMAKE_OPTS: -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015"
    configuration: Release
    platform: x86
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015"
    configuration: Debug
    platform: x86
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015 Win64"
    platform: x64
    configuration: Release
  - TARGET: vs2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_OPTS: -G"Visual Studio 14 2015 Win64"
    platform: x64
    configuration: Debug

install:
  - choco install -Y winflexbison3
  - if "%TARGET%" == "cygwin" (C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages cygwin-devel,gcc-core,file-devel,jansson,make,openssl-devel,pkg-config)
  - if "%TARGET%" == "cygwin" (set PATH=C:\cygwin64\bin;%PATH%)

build_script:
  - mkdir build
  - cd build
  - cmake %CMAKE_OPTS% -DYARA_TESTS=ON ..
  - cmake --build . --config %configuration% -- -m

test_script:
  - ctest -V

# Uncomment the lines below for enabling Remote Desktop in the Appveyor. This
# allows connecting to the remote machine and debug issues.
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
